/**
 * @file: adapters/ProjectExporter.ts
 * @description: 项目导出 — ZIP 下载与 JSON 快照（零依赖实现，无 jszip/file-saver）
 * @author: YanYuCloudCube Team <admin@0379.email>
 * @version: v1.1.0
 * @created: 2026-03-08
 * @updated: 2026-09-17
 * @status: active
 * @license: MIT
 * @copyright: Copyright (c) 2026 YanYuCloudCube Team
 * @tags: adapters,export,zip,json
 *
 * brief: 自归档版回迁；ZIP 采用 STORE（无压缩）打包，浏览器原生
 *        Blob 下载，避免引入 jszip/file-saver 运行时依赖
 */

// ── 类型 ──

export interface ExportOptions {
  projectName: string;
  includePackageJson?: boolean;
  includeTsConfig?: boolean;
  includeViteConfig?: boolean;
  includeReadme?: boolean;
}

// ── 默认配置文件生成 ──

function generatePackageJson(name: string): string {
  return JSON.stringify(
    {
      name: name.toLowerCase().replace(/\s+/g, "-"),
      private: true,
      version: "0.1.0",
      type: "module",
      scripts: {
        dev: "vite",
        build: "tsc && vite build",
        preview: "vite preview",
      },
      dependencies: {
        react: "^18.3.1",
        "react-dom": "^18.3.1",
      },
      devDependencies: {
        "@types/react": "^18.3.0",
        "@types/react-dom": "^18.3.0",
        "@vitejs/plugin-react": "^4.3.0",
        typescript: "^5.5.0",
        vite: "^6.0.0",
        tailwindcss: "^4.0.0",
        "@tailwindcss/vite": "^4.0.0",
      },
    },
    null,
    2,
  );
}

function generateTsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2020",
        useDefineForClassFields: true,
        lib: ["ES2020", "DOM", "DOM.Iterable"],
        module: "ESNext",
        skipLibCheck: true,
        moduleResolution: "bundler",
        allowImportingTsExtensions: true,
        isolatedModules: true,
        moduleDetection: "force",
        noEmit: true,
        jsx: "react-jsx",
        strict: true,
        noUnusedLocals: true,
        noUnusedParameters: true,
        noFallthroughCasesInSwitch: true,
        noUncheckedSideEffectImports: true,
      },
      include: ["src"],
    },
    null,
    2,
  );
}

function generateViteConfig(): string {
  return `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
  ],
})
`;
}

function generateReadme(name: string): string {
  return `# ${name}

Generated by YYC³ Family AI

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

## Tech Stack

- React 18 + TypeScript
- Vite
- Tailwind CSS 4

---

*Exported on ${new Date().toLocaleDateString("zh-CN")}*
`;
}

// ── ZIP（STORE 格式，无压缩）──

interface ZipEntry {
  name: Uint8Array;
  data: Uint8Array;
  crc: number;
  offset: number;
}

/** CRC-32（IEEE 802.3），查表法 */
const CRC_TABLE = (() => {
  const table = new Uint32Array(256);
  for (let i = 0; i < 256; i++) {
    let c = i;
    for (let k = 0; k < 8; k++) {
      c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    }
    table[i] = c >>> 0;
  }
  return table;
})();

function crc32(data: Uint8Array): number {
  let c = 0xffffffff;
  for (let i = 0; i < data.length; i++) {
    c = CRC_TABLE[(c ^ data[i]) & 0xff] ^ (c >>> 8);
  }
  return (c ^ 0xffffffff) >>> 0;
}

/** DOS 时间格式（本地时间，2 秒精度） */
function dosDateTime(date: Date): { time: number; date: number } {
  const time =
    (date.getHours() << 11) | (date.getMinutes() << 5) | (date.getSeconds() >> 1);
  const d =
    ((date.getFullYear() - 1980) << 9) | ((date.getMonth() + 1) << 5) | date.getDate();
  return { time, date: d };
}

class ZipWriter {
  private entries: ZipEntry[] = [];
  private chunks: BlobPart[] = [];
  private offset = 0;

  add(name: string, content: string): void {
    const encoder = new TextEncoder();
    const nameBytes = encoder.encode(name);
    const dataBytes = encoder.encode(content);
    const { time, date } = dosDateTime(new Date());

    const local = new DataView(new ArrayBuffer(30));
    local.setUint32(0, 0x04034b50, true); // local file header signature
    local.setUint16(4, 20, true); // version needed
    local.setUint16(6, 0x0800, true); // flags: UTF-8
    local.setUint16(8, 0, true); // method: STORE
    local.setUint16(10, time, true);
    local.setUint16(12, date, true);
    local.setUint32(14, crc32(dataBytes), true);
    local.setUint32(18, dataBytes.length, true); // compressed = stored
    local.setUint32(22, dataBytes.length, true); // uncompressed
    local.setUint16(26, nameBytes.length, true);
    local.setUint16(28, 0, true); // extra length

    this.chunks.push(local.buffer, nameBytes.buffer as ArrayBuffer, dataBytes.buffer as ArrayBuffer);
    this.entries.push({ name: nameBytes, data: dataBytes, crc: crc32(dataBytes), offset: this.offset });
    this.offset += 30 + nameBytes.length + dataBytes.length;
  }

  async blob(): Promise<Blob> {
    const centralStart = this.offset;
    for (const e of this.entries) {
      const central = new DataView(new ArrayBuffer(46));
      central.setUint32(0, 0x02014b50, true); // central directory signature
      central.setUint16(4, 20, true); // version made by
      central.setUint16(6, 20, true); // version needed
      central.setUint16(8, 0x0800, true); // flags: UTF-8
      central.setUint16(10, 0, true); // method: STORE
      central.setUint16(12, dosDateTime(new Date()).time, true);
      central.setUint16(14, dosDateTime(new Date()).date, true);
      central.setUint32(16, e.crc, true);
      central.setUint32(20, e.data.length, true);
      central.setUint32(24, e.data.length, true);
      central.setUint16(28, e.name.length, true);
      central.setUint16(30, 0, true); // extra
      central.setUint16(32, 0, true); // comment
      central.setUint16(34, 0, true); // disk number
      central.setUint16(36, 0, true); // internal attrs
      central.setUint32(38, 0o644 << 16, true); // external attrs (rw-r--r--)
      central.setUint32(42, e.offset, true); // local header offset
      this.chunks.push(central.buffer, e.name.buffer as ArrayBuffer);
      this.offset += 46 + e.name.length;
    }

    const end = new DataView(new ArrayBuffer(22));
    end.setUint32(0, 0x06054b50, true); // EOCD signature
    end.setUint16(4, 0, true); // disk number
    end.setUint16(6, 0, true); // central dir disk
    end.setUint16(8, this.entries.length, true);
    end.setUint16(10, this.entries.length, true);
    end.setUint32(12, this.offset - centralStart, true); // central dir size
    end.setUint32(16, centralStart, true);
    end.setUint16(20, 0, true); // comment length
    this.chunks.push(end.buffer);

    const blob = new Blob(this.chunks, { type: "application/zip" });
    this.chunks = [];
    this.entries = [];
    this.offset = 0;
    return blob;
  }
}

// ── ZIP 导出 ──

export async function exportAsZip(
  files: Record<string, string>,
  options: ExportOptions,
): Promise<void> {
  const zip = new ZipWriter();

  for (const [path, content] of Object.entries(files)) {
    zip.add(path, content);
  }

  if (options.includePackageJson !== false && !files["package.json"]) {
    zip.add("package.json", generatePackageJson(options.projectName));
  }
  if (options.includeTsConfig !== false && !files["tsconfig.json"]) {
    zip.add("tsconfig.json", generateTsConfig());
  }
  if (options.includeViteConfig !== false && !files["vite.config.ts"]) {
    zip.add("vite.config.ts", generateViteConfig());
  }
  if (options.includeReadme !== false && !files["README.md"]) {
    zip.add("README.md", generateReadme(options.projectName));
  }

  const blob = await zip.blob();
  downloadBlob(blob, `${slug(options.projectName)}-${formatDate()}.zip`);
}

// ── JSON 导出 ──

export function exportAsJson(
  files: Record<string, string>,
  options: ExportOptions,
): void {
  const exportData = {
    projectName: options.projectName,
    exportedAt: new Date().toISOString(),
    generator: "YYC³ Family AI",
    fileCount: Object.keys(files).length,
    files,
  };

  const blob = new Blob([JSON.stringify(exportData, null, 2)], {
    type: "application/json",
  });
  downloadBlob(blob, `${slug(options.projectName)}-${formatDate()}.json`);
}

// ── JSON 导入 ──

export interface ImportResult {
  success: boolean;
  projectName: string;
  files: Record<string, string>;
  fileCount: number;
  error?: string;
}

export function importFromJson(jsonString: string): ImportResult {
  try {
    const data = JSON.parse(jsonString) as {
      files?: Record<string, string>;
      projectName?: string;
    };

    if (!data.files || typeof data.files !== "object") {
      return {
        success: false,
        projectName: "",
        files: {},
        fileCount: 0,
        error: "无效的项目文件格式：缺少 files 字段",
      };
    }

    return {
      success: true,
      projectName: data.projectName || "Imported Project",
      files: data.files,
      fileCount: Object.keys(data.files).length,
    };
  } catch (err) {
    return {
      success: false,
      projectName: "",
      files: {},
      fileCount: 0,
      error: `JSON 解析失败: ${err instanceof Error ? err.message : String(err)}`,
    };
  }
}

// ── 辅助 ──

function downloadBlob(blob: Blob, fileName: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  a.click();
  URL.revokeObjectURL(url);
}

function slug(name: string): string {
  return name.replace(/\s+/g, "-").toLowerCase() || "project";
}

function formatDate(): string {
  return new Date().toISOString().slice(0, 10);
}
